version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Check Node Version
          command: node --version
      - restore_cache:
          keys:
            - node-deps-v1-{{ checksum "package-lock.json" }}
            - node-deps-v1-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node-deps-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Run Unit Tests with Coverage
          command: npm test -- --coverage
      - store_artifacts:
          path: coverage
          destination: unit-test-coverage

  deploy-aws:
    docker:
      - image: cimg/aws:2023.05 # Pre-installed with AWS CLI
    steps:
      - checkout
      - run:
          name: Deploy Build Assets to S3
          command: |
            aws s3 sync ./build s3://my-circleci-build-bucket-react --delete

  deploy-to-vercel:
    docker:
      - image: cimg/node:20.18.1
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel
      - run:
          name: Pull Vercel Environment Info
          # Uses the VERCEL_ORG_ID and VERCEL_PROJECT_ID  automatically
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
      - run:
          name: Build Project Artifacts
          command: vercel build --prod --token=$VERCEL_TOKEN
      - run:
          name: Deploy Project Artifacts to Vercel
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  build_and_test:
    jobs:
      - build
      - deploy-aws:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy-to-vercel:
          requires:
            - build
          filters:
            branches:
              only: main
